# Generated by Django 4.2.3 on 2023-07-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prd_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Img',
            field=models.ImageField(default=222, upload_to='Gallery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
